### ISSUE TITLE
Add logic to upload follow checkbox to the userevent, userclub, and usertag table

### ISSUE THREAD

**Issue by Ashley-Carlson** [Ashley-Carlson/UNC-Events-Online#14]
https://github.com/eragon5779/YCH

See here for an example of tags (side note the whole website is based off of this code)

**Comment by Ashley-Carlson** [comment]
This is redundant but these are what people can follow.

**Comment by matthew-bradow** [comment]
This one requires that the follow checkbox exists which it doesn't seem to yet

**Comment by Ashley-Carlson** [comment]
Still needs tags but need tag page

**Comment by Ashley-Carlson** [comment]
Not doing a tag page
