### ISSUE TITLE
Enable email verification

### ISSUE THREAD

**Issue by Ashley-Carlson** [Ashley-Carlson/UNC-Events-Online#32]
1. Add field to user table called `verify_string`
2. When user registers, mark their account as inactive (or have accounts default to inactive), and fill the above field with a randomly-generated string
3. Send email that links to a `verify.php` page with the `verify_string` attached (i.e. `https://uncoevents.online/verify.php?verify=randomstringhere`)
4. Mark the account the `verify_string` is attached to as active so they can login

**Comment by matthew-bradow** [comment]
This has been written into the code. After. Creating an account I did not receive an email so there's a bug but I need to be able to delete my account from the database to retest.

**Comment by matthew-bradow** [comment]
This now sends out an email but the link refuses to connect. I'm working on figuring this out.

**Comment by matthew-bradow** [comment]
Looks like it should be working but uncevents.online just needs to be updated for it to work.

**Comment by Ashley-Carlson** [comment]
We fixed the weird https error and it looks great! Thank you Matthew!
